### ISSUE TITLE
Pressure field in SCM gabls3 case doesn't change

### ISSUE THREAD

**Issue by edwardstrobach** [NCAR/ccpp-scm#230] opened 2021-01-26 21:37 UTC
Good evening,

I find that the column and surface pressure fields when running the single column model for the gabls3 case does not change.  This was determined after attempting to use the column pressure for density calculations required for an experiment that I would like to test eventually.  Ideally I would like to have both the hydrostatic and non-hydrostatic field output.  Currently, however, I do not feel comfortable using the pressure field as it is represented right now.  Is this expected with the single column model?  Thanks.

**Comment by grantfirl** [comment] 2021-02-19 22:44
This is by design. Older versions of the SCM ingested a time-series of surface pressure from the forcing, and this was written as output, but there was no commensurate change in internal vertical sigma-pressure levels, which are Eulerian and fixed in time currently. There are plans to switch the SCM to the same semi-Lagrangian vertical coordinate system as FV3. This requires a vertical remapping step for state variables as the vertical coordinate adjusts to changes in surface pressure. I'm actually not sure what you mean by hydrostatic and non-hydrostatic field output in relation to the SCM. There is no dycore in the SCM, and therefore no state vertical velocity, and there can't be such a thing as non-hydrostatic field output with the SCM.

**Comment by edwardstrobach** [comment] 2021-02-19 23:38
Okay, thanks.  My understanding of the SCM is not complete, so this extra
detail about no dycore in the SCM is helpful. Thanks

**Closed** 2021-09-27 22:23 UTC
